//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wild8.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int Id { get; set; }
        public string title { get; set; }
        public string comment1 { get; set; }
        public Nullable<int> mealId { get; set; }
        public System.DateTime commentTime { get; set; }
        public Nullable<int> userId { get; set; }
    
        public virtual Meal Meal { get; set; }
        public virtual User User { get; set; }
    }
}
