//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wild8.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MealAddOn
    {
        public int Id { get; set; }
        public Nullable<int> mealId { get; set; }
        public Nullable<int> addOnId { get; set; }
    
        public virtual AddOn AddOn { get; set; }
        public virtual Meal Meal { get; set; }
    }
}
