//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wild8.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MealType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MealType()
        {
            this.OrderMeals = new HashSet<OrderMeal>();
        }
    
        public int Id { get; set; }
        public int mealId { get; set; }
        public string type { get; set; }
        public double price { get; set; }
    
        public virtual Meal Meal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderMeal> OrderMeals { get; set; }
    }
}
